import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ListAllCars from '../components/cars/listCars'
import { CarResults, Cars, Pagination } from '../components/types'
import styles from '../styles/Home.module.css'

const Home: NextPage<{result: Cars[], pagination: Pagination}> = ({result, pagination}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CarHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListAllCars result={result} pagination={pagination}/>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch("https://api.staging.myautochek.com/v1/inventory/car/search");
  const { result, pagination }: CarResults = await res.json();
  return {
    props: {
      result,
      pagination
    },
  };
};

export default Home
